import type { HandbookDocumentContent } from "../types";

const document: HandbookDocumentContent = {
  navHtml: `<div class="nav-brand">SECURITY · DELIVERY</div>
<div class="nav-title">배포 보안 로드맵</div>
<a href="#security-flow"><span class="code">STEP</span>전체 흐름</a>
<a href="#security-design"><span class="code">01</span>설계 전</a>
<a href="#security-build"><span class="code">02</span>코드·빌드</a>
<a href="#security-release"><span class="code">03</span>배포 직전</a>
<a href="#security-after"><span class="code">04</span>배포 후</a>
<a href="#security-fe"><span class="code">FE</span>프론트엔드 배포</a>
<a href="#security-be"><span class="code">BE</span>백엔드 배포</a>
<a href="#security-db"><span class="code">DB</span>DB 배포</a>
<a href="#security-fullstack"><span class="code">FLOW</span>통합 배포 순서</a>
<a href="#security-governance"><span class="code">05</span>거버넌스·책임</a>
<a href="#security-risk"><span class="code">06</span>위험 평가</a>
<a href="#security-evidence"><span class="code">07</span>통제·증거</a>
<a href="#security-exception"><span class="code">08</span>예외·취약점</a>
<a href="#security-stop"><span class="code">GATE</span>중단 기준</a>
<a href="#security-sources"><span class="code">REF</span>기준 문서</a>`,
  mainHtml: `<header class="hero">
<div class="hero-serial"><span>DOC : SECURITY-DELIVERY-ROADMAP</span><span>ORDER : DESIGN → BUILD → RELEASE → VERIFY</span><span>LANG : KO</span></div>
<h1>코드를 운영에 올리기 전,<br>보안에서 무엇을 확인할까</h1>
<p class="hero-sub">보안 도구 목록이 아니라 배포 순서에 맞춘 실행 가이드입니다. 매 단계에서 확인할 질문, 남길 증거, 배포를 멈춰야 할 조건을 함께 봅니다.</p>
<div class="hero-meta">PRACTICAL RELEASE PATH · UPDATED 2026-10</div>
</header>
<section id="security-flow"><div class="ch-head"><span class="ch-code">STEP</span><h2>한눈에 보는 배포 보안 흐름</h2></div>
<table><tr><th>단계</th><th>먼저 확인할 것</th><th>완료 증거</th></tr>
<tr><td>1. 설계</td><td>보호할 데이터, 사용자 역할, 외부 입력, 신뢰 경계</td><td>간단한 데이터 흐름도와 권한표</td></tr>
<tr><td>2. 구현</td><td>입력 검증, 서버 인가, secret 분리, 안전한 오류</td><td>negative test와 secret scan 결과</td></tr>
<tr><td>3. 빌드</td><td>의존성·이미지 취약점, lockfile, 산출물 내 secret</td><td>고정된 버전과 스캔 리포트</td></tr>
<tr><td>4. 배포</td><td>TLS, 헤더, IAM, 네트워크, DB 백업, 롤백</td><td>승인된 체크리스트와 배포 ID</td></tr>
<tr><td>5. 검증</td><td>인증 우회, 타인 데이터 접근, 로그·알림 작동</td><td>smoke test, audit event, 모니터링 링크</td></tr></table>
<div class="callout"><span class="co-label">가장 중요한 원칙</span><p>브라우저의 메뉴 숨김이나 환경 변수 이름은 보안 경계가 아닙니다. 중요한 값과 권한 판정은 서버에서 통제하고, 배포 후에도 폐기·롤백·추적할 수 있어야 합니다.</p></div></section>
<section id="security-design"><div class="ch-head"><span class="ch-code">01</span><h2>설계 전 — 경계부터 그린다</h2></div>
<ul><li>개인정보, 결제, 파일, 관리자 기능처럼 사고 시 영향이 큰 자산을 표시한다.</li><li>익명·일반·관리자·서비스 계정이 할 수 있는 행동을 표로 만든다.</li><li>클라이언트, API, DB, 외부 SaaS 사이에서 데이터가 이동하는 경계를 그린다.</li><li>사용자 입력뿐 아니라 webhook, 파일, URL, 큐 메시지도 불신 입력으로 본다.</li></ul></section>
<section id="security-build"><div class="ch-head"><span class="ch-code">02</span><h2>코드·빌드 — 자동으로 실패하게 만든다</h2></div>
<table><tr><th>검사</th><th>실패 조건</th><th>대응</th></tr><tr><td>Secret scan</td><td>토큰·private key·운영 접속 문자열 탐지</td><td>커밋 삭제가 아니라 즉시 폐기·재발급</td></tr><tr><td>SAST·lint</td><td>injection, 위험 함수, 검증 누락</td><td>원인 수정 또는 만료일 있는 예외 승인</td></tr><tr><td>Dependency scan</td><td>실제 사용 경로의 치명적 취약점</td><td>업데이트·완화 후 재검사</td></tr><tr><td>Authorization test</td><td>익명·타 사용자·타 tenant 접근 성공</td><td>서버 정책 수정 후 회귀 테스트 추가</td></tr></table></section>
<section id="security-release"><div class="ch-head"><span class="ch-code">03</span><h2>배포 직전 — 변경점 중심으로 승인한다</h2></div>
<div class="checklist"><strong>RELEASE SECURITY GATE</strong><ul><li>운영 secret은 코드·이미지·프론트 번들에 없다.</li><li>배포 계정은 필요한 리소스와 시간에만 권한이 있다.</li><li>HTTPS 강제, 쿠키 속성, CORS allowlist가 운영값이다.</li><li>DB migration과 권한 변경은 되돌리는 절차가 있다.</li><li>로그에 token, password, 주민번호·카드번호가 남지 않는다.</li><li>health check와 rollback 명령을 실제로 실행할 수 있다.</li></ul></div></section>
<section id="security-after"><div class="ch-head"><span class="ch-code">04</span><h2>배포 후 — 정상뿐 아니라 차단도 확인한다</h2></div>
<p class="lede">로그인 성공만 확인하지 말고 실패해야 하는 요청을 실행합니다.</p><ul><li>인증 없이 보호 API 호출 → 401</li><li>일반 계정으로 관리자 API 호출 → 403 또는 정책상 404</li><li>A 계정으로 B 계정의 객체 ID 조회 → 데이터 미노출</li><li>만료·폐기된 token 재사용 → 거부 및 감사 로그</li><li>비정상 로그인·권한 변경 → 알림과 담당자 연결</li></ul></section>
<section id="security-fe"><div class="ch-head"><span class="ch-code">FE</span><h2>프론트엔드 배포 보안</h2></div>
<p class="lede">프론트엔드는 사용자의 브라우저에서 실행되므로 코드와 공개 환경 변수는 공격자도 모두 볼 수 있습니다. FE 배포 보안의 목표는 코드를 숨기는 것이 아니라 <strong>신뢰하면 안 되는 클라이언트에 권한과 secret을 두지 않고, 공급망·브라우저 실행·캐시 경계를 통제하는 것</strong>입니다.</p>
<h3><span class="h3-tag">FE-1</span>보호 자산과 공격면</h3>
<table><tr><th>자산·경계</th><th>주요 위험</th><th>핵심 개념</th></tr><tr><td>JavaScript bundle</td><td>secret 포함, 변조된 dependency, source map 노출</td><td>공개 산출물, supply-chain integrity</td></tr><tr><td>DOM·브라우저 API</td><td>XSS, DOM clobbering, 위험한 URL·HTML sink</td><td>출력 인코딩, sanitization, CSP</td></tr><tr><td>Cookie·token</td><td>XSS 탈취, CSRF, 장기 bearer token</td><td>HttpOnly·Secure·SameSite, token 최소화</td></tr><tr><td>CDN·cache</td><td>사용자별 응답 cache, 오래된 취약 bundle, purge 실패</td><td>cache key, immutable asset, HTML no-cache 정책</td></tr><tr><td>Third-party script</td><td>태그 매니저·analytics 침해로 전체 origin 권한 획득</td><td>최소화, CSP, SRI, vendor governance</td></tr></table>
<h3><span class="h3-tag">FE-2</span>배포 전 절차</h3><ol><li><strong>빌드 입력 고정:</strong> lockfile과 신뢰된 registry를 사용하고 install script·새 dependency·third-party script 변경을 리뷰한다.</li><li><strong>공개 설정 검사:</strong> <code>VITE_*</code>, <code>NEXT_PUBLIC_*</code>와 bundle 문자열에서 secret, 내부 URL, debug flag를 검사한다.</li><li><strong>위험 sink 검토:</strong> <code>innerHTML</code>, 동적 script, URL redirect, markdown·rich text renderer의 신뢰 경계를 확인한다.</li><li><strong>브라우저 정책 설계:</strong> CSP를 report-only로 관찰한 뒤 nonce·hash 중심 정책으로 강화하고 frame·object·base URI를 제한한다.</li><li><strong>인증 경계 확인:</strong> route guard와 버튼 숨김은 UX일 뿐이며 모든 권한은 BE에서 다시 판정되는지 negative test한다.</li></ol>
<h3><span class="h3-tag">FE-3</span>배포·캐시·롤백</h3><ul><li>asset filename은 content hash를 사용하고 긴 immutable cache를 적용하되, HTML은 새 manifest를 빠르게 받도록 별도 cache 정책을 둔다.</li><li>새 HTML이 아직 배포되지 않은 chunk를 참조하지 않도록 asset 업로드 → 가용성 확인 → HTML 전환 순서를 쓴다.</li><li>source map은 공개 필요성을 판단하고, 오류 분석 서비스에 올릴 때도 접근 통제와 source 노출 범위를 제한한다.</li><li>service worker는 별도 릴리스 자산으로 보고 cache version, activation, 강제 업데이트와 취약 버전 제거 절차를 시험한다.</li><li>롤백 시 이전 FE가 현재 API·schema와 호환되는지 확인한다. 단순 CDN 되돌리기가 안전한 롤백을 보장하지 않는다.</li></ul>
<h3><span class="h3-tag">FE-4</span>사례 — 운영 API Key가 bundle에 포함됨</h3><div class="callout risk"><span class="co-label">INCIDENT CASE</span><p>개발자가 외부 SaaS의 쓰기 권한 API key를 <code>VITE_VENDOR_KEY</code>에 넣었습니다. CI secret으로 저장했지만 빌드 시 bundle에 치환되어 브라우저에서 누구나 읽을 수 있었습니다. 공격자는 key로 데이터를 생성·삭제했습니다.</p></div>
<table><tr><th>잘못된 판단</th><th>올바른 설계</th></tr><tr><td>CI에 저장했으니 클라이언트에서도 secret이다.</td><td>브라우저에 전달되는 순간 공개값이다.</td></tr><tr><td>난독화하면 숨길 수 있다.</td><td>BE proxy가 secret을 보유하고 사용자 권한·요청량을 검증한다.</td></tr><tr><td>Git에서 지우면 해결된다.</td><td>key 폐기·재발급, 사용 로그 조사, bundle·CDN purge, 회귀 scan이 필요하다.</td></tr></table>
<div class="checklist"><strong>FE RELEASE EVIDENCE</strong><ul><li>bundle·source map secret scan 결과</li><li>dependency·third-party script diff</li><li>CSP violation 확인과 보안 헤더 응답</li><li>XSS fixture와 타 권한 route/API negative test</li><li>CDN cache·service worker 갱신 및 rollback 결과</li></ul></div></section>
<section id="security-be"><div class="ch-head"><span class="ch-code">BE</span><h2>백엔드 배포 보안</h2></div>
<p class="lede">백엔드는 사용자 입력이 권한 있는 동작과 데이터 변경으로 바뀌는 신뢰 경계입니다. BE 배포 보안은 <strong>인증·인가·입력·외부 호출·secret·실행 권한·관측 가능성</strong>을 요청 단위로 통제하는 일입니다.</p>
<h3><span class="h3-tag">BE-1</span>보호 자산과 공격면</h3><table><tr><th>경로</th><th>대표 위험</th><th>필수 통제</th></tr><tr><td>Public API</td><td>인증 우회, IDOR, injection, mass assignment</td><td>schema 검증, 서버 인가, parameterized query</td></tr><tr><td>Webhook</td><td>위조, replay, 중복 상태 변경</td><td>signature·timestamp, event ledger, idempotency</td></tr><tr><td>외부 URL 호출</td><td>SSRF, metadata·내부망 접근</td><td>scheme·host allowlist, DNS·redirect 재검증, egress 통제</td></tr><tr><td>Queue·worker</td><td>권한 context 유실, poison message, 무한 재시도</td><td>검증된 envelope, tenant scope, DLQ, retry budget</td></tr><tr><td>관리 API</td><td>고권한 남용과 대량 유출</td><td>step-up auth, JIT 권한, 승인·감사</td></tr></table>
<h3><span class="h3-tag">BE-2</span>배포 전 절차</h3><ol><li>API 계약 diff에서 새 endpoint, field, error, 권한과 데이터 노출 변화를 찾는다.</li><li>anonymous, expired, foreign-user, foreign-tenant, downgraded-role fixture로 인가를 시험한다.</li><li>client가 보낸 userId·role·tenantId·가격·상태가 서버에서 재계산되는지 확인한다.</li><li>업로드, URL fetch, template, query, command, deserialization 같은 위험 sink까지 데이터 흐름을 추적한다.</li><li>새 secret·IAM·network egress·DB 권한을 최소 범위로 부여하고 로그 redaction을 검증한다.</li><li>timeout, circuit breaker, concurrency limit, request size와 rate limit을 업무별로 정한다.</li></ol>
<h3><span class="h3-tag">BE-3</span>점진 배포와 권한 변경</h3><ul><li>artifact digest 하나를 환경 간 승격하고 canary·blue/green으로 오류율, latency, deny율, DB 부하를 비교한다.</li><li>새 권한 정책은 shadow evaluation으로 기존 결정과 차이를 기록한 뒤 enforce한다.</li><li>token claim·permission schema가 바뀌면 구 token을 어떻게 처리할지 명시한다. UI만 새 권한을 반영하면 안 된다.</li><li>feature flag는 보안 통제를 우회하는 숨은 경로가 되지 않게 서버 측 default-deny와 감사 로그를 둔다.</li><li>rollback은 binary뿐 아니라 message format, cache, migration, 외부 side effect와 호환돼야 한다.</li></ul>
<h3><span class="h3-tag">BE-4</span>사례 — 보고서 다운로드 IDOR</h3><div class="callout risk"><span class="co-label">INCIDENT CASE</span><p><code>GET /reports/{id}</code>가 로그인 여부만 확인하고 report id로 조회했습니다. FE에서는 타 보고서 링크가 보이지 않았지만 공격자가 id를 바꿔 다른 tenant의 보고서를 다운로드했습니다.</p></div>
<p><strong>수정:</strong> 세션의 actor tenant와 resource tenant를 DB 조회 조건에 함께 넣고, object storage signed URL도 짧은 TTL과 actor-bound 발급으로 바꿉니다. A tenant token × B tenant report fixture, 응답 body·DB·audit event를 회귀 테스트에 포함합니다.</p>
<div class="checklist"><strong>BE RELEASE EVIDENCE</strong><ul><li>API·권한·데이터 계약 diff</li><li>인증·인가·tenant negative test</li><li>SAST·SCA·container·secret scan triage</li><li>runtime IAM·egress·DB permission diff</li><li>canary 기준, audit event, revoke·rollback 실행 결과</li></ul></div></section>
<section id="security-db"><div class="ch-head"><span class="ch-code">DB</span><h2>데이터베이스 배포 보안</h2></div>
<p class="lede">DB 배포는 단순 schema 변경이 아니라 데이터의 기밀성·무결성·가용성과 복구 가능성을 동시에 바꿉니다. 특히 migration은 애플리케이션 롤백만으로 되돌릴 수 없는 경우가 많으므로 <strong>전후 호환, 최소 권한, 검증 가능한 변환, 복원 가능성</strong>이 핵심입니다.</p>
<h3><span class="h3-tag">DB-1</span>변경 유형별 위험</h3><table><tr><th>변경</th><th>보안·운영 위험</th><th>안전한 접근</th></tr><tr><td>컬럼·테이블 추가</td><td>민감정보 수집 확대, 잘못된 default, storage 급증</td><td>분류·보존 기준, nullable 추가 후 backfill</td></tr><tr><td>타입·제약 변경</td><td>잘림, 무결성 손실, 긴 lock</td><td>사전 query, shadow column, batch 검증</td></tr><tr><td>권한·RLS 변경</td><td>전체 tenant 노출 또는 서비스 중단</td><td>policy test, 별도 role, default deny</td></tr><tr><td>Backfill</td><td>잘못된 대량 변환, audit 오염, replica lag</td><td>작은 batch, checkpoint, rate limit, before/after count</td></tr><tr><td>삭제·drop</td><td>영구 손실, 구버전 앱 장애</td><td>사용 중단 확인, 보존·backup, 지연된 contract</td></tr></table>
<h3><span class="h3-tag">DB-2</span>Expand–Migrate–Contract</h3><ol><li><strong>Expand:</strong> 기존 앱과 호환되는 새 컬럼·테이블·index를 추가한다.</li><li><strong>Deploy compatible code:</strong> 구·신 구조를 함께 읽거나 dual-write하되 source of truth와 실패 처리를 정한다.</li><li><strong>Migrate:</strong> batch backfill을 수행하고 row count, checksum, null·duplicate, tenant별 표본을 검증한다.</li><li><strong>Switch:</strong> read path를 새 구조로 전환하고 지표·오류·replica lag를 관찰한다.</li><li><strong>Contract:</strong> 모든 구버전과 job의 사용 중단이 증명된 뒤 구 컬럼·권한을 제거한다.</li></ol>
<div class="callout warn"><span class="co-label">Dual-write 주의</span><p>dual-write는 원자성 실패와 데이터 불일치를 새로 만듭니다. 같은 transaction 가능 여부, retry·idempotency, reconciliation query, 어느 쪽이 source of truth인지 먼저 정합니다.</p></div>
<h3><span class="h3-tag">DB-3</span>계정·권한·감사</h3><ul><li>application runtime, migration, read-only analytics, backup 계정을 분리한다.</li><li>앱 계정에 schema 변경·role 생성·전체 database 관리 권한을 주지 않는다.</li><li>migration credential은 배포 시간에만 발급하고 사용 후 폐기한다.</li><li>개발·staging에서 운영 dump 원문을 쓰지 않고 masking·synthetic data를 사용한다.</li><li>DDL, role·grant 변경, 대량 export, 민감 table 조회를 감사하고 audit 관리자와 DB 관리자를 분리한다.</li></ul>
<h3><span class="h3-tag">DB-4</span>사례 — NOT NULL migration이 운영을 잠금</h3><div class="callout risk"><span class="co-label">INCIDENT CASE</span><p>대형 테이블에 default 값을 가진 NOT NULL 컬럼을 한 번에 추가했습니다. DB가 table rewrite·lock을 수행하면서 API가 timeout되고, 급히 앱만 롤백했지만 migration은 이미 일부 적용돼 상태가 더 복잡해졌습니다.</p></div>
<p><strong>개선:</strong> nullable 컬럼 추가 → 새 앱 write → 작은 batch backfill → 누락 query 0건 확인 → 제약을 안전한 방식으로 검증 → 마지막에 NOT NULL 적용 순서로 분리합니다. lock timeout, statement timeout, replica lag, 중단 명령과 resume checkpoint를 사전에 둡니다.</p>
<div class="checklist"><strong>DB RELEASE EVIDENCE</strong><ul><li>schema·role·RLS diff와 영향 query</li><li>운영 규모에 가까운 실행 시간·lock·disk 측정</li><li>backup 시각, restore test와 RPO·RTO 확인</li><li>row count·checksum·tenant 표본·무결성 검증</li><li>중단·resume·roll-forward·rollback 판단표</li></ul></div></section>
<section id="security-fullstack"><div class="ch-head"><span class="ch-code">FLOW</span><h2>FE·BE·DB가 함께 바뀔 때의 통합 배포 순서</h2></div>
<p class="lede">세 계층을 동시에 교체하면 부분 실패 시 호환성이 깨집니다. DB는 전후 호환 구조를 먼저 만들고, BE는 구·신 계약을 모두 처리한 뒤, FE는 마지막에 새 기능을 노출하는 순서가 기본입니다.</p>
<table><tr><th>순서</th><th>배포</th><th>보안·검증 기준</th><th>되돌림</th></tr><tr><td>0</td><td>계약·위협 모델 확정</td><td>데이터 분류, 권한표, API·schema compatibility</td><td>아직 변경 없음</td></tr><tr><td>1</td><td>DB expand</td><td>새 구조는 비활성·최소 권한, 구 앱 정상</td><td>가능하면 roll-forward 우선</td></tr><tr><td>2</td><td>BE compatible version</td><td>구·신 요청, 인가, dual path negative test</td><td>이전 BE가 expanded DB와 호환</td></tr><tr><td>3</td><td>Backfill·검증</td><td>무결성, tenant 격리, 부하·lag</td><td>중단·resume 또는 보정</td></tr><tr><td>4</td><td>FE 배포·flag 활성화</td><td>bundle·CSP·권한·캐시 검증</td><td>flag off 또는 이전 FE</td></tr><tr><td>5</td><td>DB contract</td><td>구 client·job·token 사용이 0임을 증명</td><td>backup만 믿지 말고 별도 승인</td></tr></table>
<h3><span class="h3-tag">FLOW-1</span>통합 사례 — 사용자 역할 체계 변경</h3><p><code>admin/user</code>를 <code>owner/editor/viewer</code>로 바꾼다면 DB enum부터 바로 교체하지 않습니다. DB에 새 role 표현을 추가하고 매핑을 backfill한 뒤, BE가 구·신 role을 모두 읽되 새 중앙 정책으로 결정하게 합니다. audit에서 decision 차이를 관찰하고, FE는 새 역할 UI를 마지막에 노출합니다. 구 token claim과 background job이 사라진 뒤에만 구 role을 제거합니다.</p>
<div class="callout"><span class="co-label">통합 Go/No-Go</span><p>각 계층의 개별 테스트가 통과해도 버전 조합 <strong>구 FE–신 BE–확장 DB</strong>, <strong>신 FE–신 BE–확장 DB</strong>, rollback 조합이 안전해야 배포할 수 있습니다. 호환 가능한 조합을 release matrix로 명시합니다.</p></div></section>
<section id="security-governance"><div class="ch-head"><span class="ch-code">05</span><h2>보안 거버넌스 — 누가 결정하고 누가 증명하는가</h2></div>
<p class="lede">보안관리자의 핵심 역할은 모든 코드를 직접 검사하는 것이 아니라 위험의 소유자, 통제의 운영자, 독립 검증자, 예외 승인자를 분리하고 증거가 남는 시스템을 만드는 것입니다.</p>
<table><tr><th>역할</th><th>책임</th><th>분리해야 하는 결정</th></tr><tr><td>서비스 오너</td><td>자산·업무 영향·가용성 목표 정의</td><td>잔여 위험 수용</td></tr><tr><td>개발팀</td><td>안전한 설계·구현·테스트·수정</td><td>자신이 만든 통제의 최종 감사</td></tr><tr><td>플랫폼·운영</td><td>CI/CD, IAM, 런타임, 백업 통제 운영</td><td>운영 접근의 자기 승인</td></tr><tr><td>보안 담당</td><td>위협 모델, 통제 기준, 검증, 예외 추적</td><td>사업 영향의 단독 수용</td></tr><tr><td>데이터·개인정보 오너</td><td>분류, 보존, 삭제, 제3자 제공 기준</td><td>기술팀의 임의 보존</td></tr></table>
<h3><span class="h3-tag">5.1</span>최소 RACI 산출물</h3><ul><li>시스템·데이터·repository·cloud account마다 owner와 deputy를 지정한다.</li><li>Critical 취약점, 운영 secret 노출, 개인정보 사고의 호출 경로와 응답 시간을 정한다.</li><li>배포 승인자와 긴급 변경 승인자를 분리하고, 사후 검토 기한을 둔다.</li><li>분기별 접근 검토와 연 1회 이상 tabletop·복구 훈련을 일정에 넣는다.</li></ul></section>
<section id="security-risk"><div class="ch-head"><span class="ch-code">06</span><h2>위험 평가 — 점수보다 공격 경로를 설명한다</h2></div>
<p>위험은 보통 <strong>가능성 × 영향</strong>으로 정리하지만 숫자만으로 승인하지 않습니다. 공격 전제, 노출 자산, 기존 통제, 탐지 가능성, 업무 영향을 함께 기록합니다.</p>
<table><tr><th>질문</th><th>확인 내용</th><th>예시 증거</th></tr><tr><td>무엇이 노출되는가?</td><td>기밀성·무결성·가용성·개인정보·금전</td><td>data inventory, 업무 영향 분석</td></tr><tr><td>누가 어디서 공격하는가?</td><td>익명, 인증 사용자, 내부자, 공급망과 진입점</td><td>abuse case, trust boundary</td></tr><tr><td>현재 무엇이 막는가?</td><td>예방·탐지·대응 통제와 우회 가능성</td><td>설정, 테스트, alert, runbook</td></tr><tr><td>실패하면 얼마나 큰가?</td><td>tenant 수, 레코드 수, 중단 시간, 법적 영향</td><td>scope query, RTO/RPO, 계약</td></tr></table>
<div class="semantic-card"><span class="sc-label">RISK RECORD</span><br>risk_id · asset · threat actor · entry point · scenario · existing controls · likelihood · impact · owner · treatment · due date · residual risk · approver · evidence links</div>
<h3><span class="h3-tag">6.1</span>처리 방식</h3><ul><li><strong>Mitigate</strong>: 통제를 추가해 가능성이나 영향을 낮춘다.</li><li><strong>Avoid</strong>: 위험한 기능·데이터 수집·노출 경로를 제거한다.</li><li><strong>Transfer</strong>: 보험·계약·managed service로 일부 책임을 이전하되 감독 책임은 남는다.</li><li><strong>Accept</strong>: 권한 있는 업무 오너가 기간·근거·잔여 위험을 명시해 수용한다.</li></ul></section>
<section id="security-evidence"><div class="ch-head"><span class="ch-code">07</span><h2>통제 카탈로그와 증거 체계</h2></div>
<p class="lede">정책 문구가 아니라 실제로 작동하고 있음을 보여주는 증거가 있어야 통제입니다. 통제마다 목적, 범위, owner, 빈도, 검증 방법, 실패 시 조치를 등록합니다.</p>
<table><tr><th>통제 유형</th><th>예시</th><th>좋은 증거</th></tr><tr><td>예방</td><td>branch protection, least privilege, schema validation</td><td>설정 export, policy test, 거부 로그</td></tr><tr><td>탐지</td><td>secret scan, 이상 로그인, 권한 변경 alert</td><td>탐지 rule, test event, 알림 수신 기록</td></tr><tr><td>대응</td><td>token revoke, 격리, rollback, incident runbook</td><td>훈련 timeline, 실행 로그, 복구 결과</td></tr><tr><td>보상</td><td>패치 전 WAF rule, 임시 접근 차단</td><td>적용 범위, 만료일, 영구 수정 ticket</td></tr></table>
<h3><span class="h3-tag">7.1</span>릴리스 보안 패킷</h3><ol><li>변경 요약과 데이터·권한·외부 노출 diff</li><li>위협 모델 또는 변경된 abuse case</li><li>SAST·SCA·secret·IaC·container scan 결과와 triage</li><li>인가·tenant·입력·session negative test</li><li>SBOM 또는 dependency manifest와 artifact digest</li><li>배포·rollback·migration·관측 계획</li><li>미해결 위험, owner, 기한, 승인자</li></ol></section>
<section id="security-exception"><div class="ch-head"><span class="ch-code">08</span><h2>취약점·예외·공급망 관리</h2></div>
<h3><span class="h3-tag">8.1</span>취약점 triage</h3><p>CVSS 숫자만 보지 말고 우리 환경에서의 도달 가능성, 노출된 기능, 공격 난이도, 실제 exploit, 데이터 민감도, 보상 통제를 평가합니다. 오탐으로 닫을 때도 근거와 재검토 조건을 남깁니다.</p>
<table><tr><th>우선순위 신호</th><th>조치</th></tr><tr><td>인터넷 노출 + 인증 전 RCE·인증 우회·tenant escape</td><td>즉시 차단·격리·긴급 수정, 사고 여부 조사</td></tr><tr><td>실제 사용 경로의 알려진 exploit</td><td>정상 변경보다 우선해 패치 또는 기능 제거</td></tr><tr><td>도달 불가 또는 강한 보상 통제</td><td>증거와 재평가 기한을 두고 추적</td></tr></table>
<h3><span class="h3-tag">8.2</span>예외 승인 최소 조건</h3><ul><li>대상 통제와 미준수 이유, 업무 필요성을 구체적으로 쓴다.</li><li>영향 범위와 최악 시나리오, 보상 통제를 검증한다.</li><li>위험 owner와 승인자, 종료일, 영구 수정 ticket을 둔다.</li><li>범위·환경·공격 정보가 바뀌면 만료 전이라도 재평가한다.</li></ul></section>
<section id="security-stop"><div class="ch-head"><span class="ch-code">GATE</span><h2>이 경우 배포를 멈춘다</h2></div>
<div class="callout risk"><span class="co-label">NO-GO</span><p>운영 secret 노출, 인증 우회, cross-tenant 접근, 암호화되지 않은 민감정보 전송, 복구 불가능한 migration, 치명 취약점의 악용 경로가 확인되면 일정과 무관하게 중단합니다. owner·완화책·만료일 없는 “나중에 수정”은 승인으로 보지 않습니다.</p></div></section>
<section id="security-sources"><div class="ch-head"><span class="ch-code">REF</span><h2>기준 문서와 적용법</h2></div><ul><li><a href="https://owasp.org/projects/asvs" target="_blank" rel="noreferrer">OWASP ASVS 5.0</a> — 웹 애플리케이션 기술 통제의 검증 요구사항과 테스트 추적에 사용합니다.</li><li><a href="https://csrc.nist.gov/pubs/sp/800/218/final" target="_blank" rel="noreferrer">NIST SP 800-218 SSDF</a> — 조직 준비, 소프트웨어 보호, 안전한 생산, 취약점 대응을 SDLC에 통합할 때 사용합니다.</li></ul><div class="callout"><span class="co-label">적용 원칙</span><p>표준은 체크박스 원본이 아니라 공통 언어입니다. 서비스의 데이터 민감도와 공격면을 기준으로 적용 범위를 정하고, 각 요구사항을 실제 통제와 증거 링크에 매핑합니다.</p></div></section>`,
};

export default document;
