export const reviewedAt = "2026-09-29";
export const moneySources = {
  gdp: { title: "미국 BEA · GDP의 의미와 통계 읽기", url: "https://www.bea.gov/resources/learning-center/what-to-know-gdp", note: "실질·명목 GDP, 계절조정과 속보·수정 추계의 차이를 설명합니다. 미국 발표 방식과 한국 통계의 단위·연율 표기는 구분합니다." },
  isa: { title: "전국투자자교육협의회 · ISA와 연금계좌", url: "https://www.kcie.or.kr/mobile/yeouitv/cafeWebBook/web_view?type=3&series_idx=&content_idx=1822", note: "계좌 구조 학습 자료. 과거 연도 수치가 포함되어 있어 가입·이체 시점의 시행 규정과 상품 설명서를 재확인합니다." },
  pension: { title: "국세청 · 연금계좌 세액공제", url: "https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7875&mi=6449", note: "공제 대상·한도·소득 구간 확인. 납입한도와 공제한도, 국세와 지방소득세를 구분합니다." },
  tax: { title: "국세청 · 종합소득세 세액계산 흐름도", url: "https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?mi=2226&cntntsId=7666", note: "세금 계산의 순서에 대한 근거. 개별 소득의 신고 여부와 적용 연도는 별도 확인합니다." },
  rates: { title: "한국은행 · 금리란 무엇일까요?", url: "https://www.bok.or.kr/portal/bbs/B0000216/view.do?nttId=10061677&menuNo=20064", note: "금리와 경제의 관계를 설명하는 기초 교육 자료이며 현재 금리 수치가 아닙니다." },
  exchange: { title: "한국은행 · 환율이란 무엇인가요?", url: "https://www.bok.or.kr/portal/bbs/B0000216/view.do?nttId=10061684&menuNo=200647&pageIndex=", note: "환율의 정의와 변동 경로를 이해하는 자료이며 현재 환율 예측이 아닙니다." },
  loans: { title: "KB캐피탈 · DSR·DTI·LTV와 스트레스 DSR", url: "https://m.kbcapital.co.kr/aboutus/cmpgdnc/finLifeDtl.kbc?blbdSeqno=107206", note: "금융회사에서 제공한 2024년 개념 설명입니다. 당시 한도·예외·도입 일정은 현재 규정으로 사용하지 않습니다." },
  inflation: { title: "한국은행 · 인플레이션이란 무엇인가요?", url: "https://www.bok.or.kr/portal/bbs/B0000216/view.do?menuNo=20064&nttId=165576", note: "물가와 구매력의 개념 학습 자료. 현재 물가 전망으로 사용하지 않습니다." },
  crypto: { title: "금융위원회 · 가상자산이용자보호법 시행 안내", url: "https://www.fsc.go.kr/no010101/82682", note: "2024년 시행 안내. 이용자 보호와 투자자산의 안전성 보장은 다르며 후속 개정은 별도 확인합니다." },
  wallet: { title: "Bitcoin.org · 지갑 보안", url: "https://bitcoin.org/en/secure-your-wallet", note: "비트코인 지갑의 보관·백업 원칙. 다른 네트워크의 동작이나 자산의 가치를 보증하지 않습니다." },
  housing: { title: "HUG · 전세계약 전 등기부등본 확인", url: "https://www.khug.or.kr/jeonse/web/s03/s030105.jsp", note: "등기와 선순위 권리의 기초. 열람 절차·보증 요건·법적 우선순위는 계약 시점의 규정과 개별 사실관계를 확인합니다." },
  stocks: { title: "미국 SEC Investor.gov · 주식의 기초", url: "https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks", note: "주식의 소유권·수익·위험 개념. 미국 거래·세금 제도를 한국에 그대로 적용하지 않습니다." },
  etf: { title: "미국 SEC Investor.gov · ETF", url: "https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-2", note: "ETF 구조·가격·비용 이해용. 국내 상품의 과세·거래 규칙은 해당 설명서에서 확인합니다." },
  ecos: { title: "한국은행 ECOS · 경제통계시스템", url: "https://ecos.bok.or.kr/", note: "국민계정·금리·환율·물가와 통계 공표 일정의 검색 출발점입니다. 선택한 통계표의 단위·대상 기간·계절조정·수정 여부를 확인합니다." },
  kosis: { title: "KOSIS · 국가통계포털", url: "https://kosis.kr/", note: "생산·소매판매·고용 등 국내 실물 통계 검색 경로입니다. 경제일반·경기, 광업·제조업, 도소매·서비스 분류에서 원자료와 설명을 함께 확인합니다." },
  cli: { title: "OECD · 경기선행지수(CLI)의 정의", url: "https://www.oecd.org/en/data/indicators/composite-leading-indicator-cli.html", note: "장기 추세 주변의 경기 전환 방향을 조기에 살피는 지표입니다. 정량적인 성장률 전망이나 매매 시점 예측으로 사용하지 않습니다." },
  recessions: { title: "NBER · 미국 경기순환 판정 FAQ", url: "https://www.nber.org/research/business-cycle-dating/business-cycle-dating-procedure-frequently-asked-questions", note: "확장·침체, 여러 실물지표를 함께 보는 이유와 사후 판정의 시차를 설명합니다. 미국 판정 방식이며 한국의 공식 경기 판정과는 구분합니다." },
  pmi: { title: "S&P Global · PMI와 확산지수 FAQ", url: "https://www.spglobal.com/market-intelligence/en/solutions/products/resources/pmi-faq", note: "PMI의 조사 방식·50 기준점·확산지수 의미를 확인하는 자료입니다. 지수 포인트를 생산량 증가율로 환산하지 않고 제조업·서비스업 및 조사 기관을 구별합니다." },
  yieldCurve: { title: "FRED · 미국 10년−2년 국채금리차 (T10Y2Y)", url: "https://fred.stlouisfed.org/series/T10Y2Y", note: "미국 장단기 금리차의 정의와 원자료입니다. 금리차는 퍼센트포인트로 해석하며 두 만기의 금리 움직임과 원인을 함께 봅니다. 현재 수치는 이 사이트에 자동 반영되지 않습니다." },
  creditSpread: { title: "FRED · ICE BofA 미국 하이일드 OAS", url: "https://fred.stlouisfed.org/series/BAMLH0A0HYM2", note: "미국 투자등급 미만 회사채의 옵션조정 스프레드 정의를 확인합니다. 실제 데이터는 원사이트에서 열람하며 국내 신용 위험과 동일시하지 않습니다." },
  lending: { title: "미국 연방준비제도 · 은행 대출태도조사(SLOOS)", url: "https://www.federalreserve.gov/data/sloos.htm", note: "은행의 대출 기준·조건과 기업·가계의 대출 수요를 구분하는 조사입니다. 일반적으로 분기별 자료이며 미국 은행 조사라는 범위를 유지합니다." },
  inventory: { title: "FRED / 미국 Census Bureau · 재고/판매 비율", url: "https://fred.stlouisfed.org/series/ISRATIO", note: "미국 전체 사업체 재고/판매 비율의 월간 계절조정 자료입니다. 업종·기업 자료와 집계 범위를 맞추며 재고와 판매 각각의 변화도 확인합니다." },
  financialStatements: { title: "미국 SEC · 재무제표 읽기 기초", url: "https://www.sec.gov/about/reports-publications/investorpubsbegfinstmtguide", note: "재무상태표·손익계산서·현금흐름표의 역할과 매출·비용·이익의 관계를 설명합니다. 정상화 이익과 업종 관찰표는 이 페이지에서 구성한 학습용 해석입니다." },
  dart: { title: "금융감독원 DART · 기업 공시 원문", url: "https://dart.fss.or.kr/", note: "회사명 검색 후 정기보고서의 사업 내용·연결재무제표·주석을 확인합니다. 정정보고서와 연결·별도 구분에 유의하며 기업의 전망을 확정 사실로 보지 않습니다." },
  micronCycle: { title: "Micron · 2025 Form 10-K, 산업 사이클 위험 (PDF)", url: "https://s25.q4cdn.com/621799436/files/doc_financials/2025/ar/2025-Form-10-K.pdf", note: "Item 1A의 메모리 산업 수급·가격·고정비 관련 위험을 참고합니다. 개별 회사의 과거 공시이며 현재 업황 진단이나 해당 종목의 투자 추천이 아닙니다." },
};
