export type PracticalExample = {
  scenario: string;
  actions: string[];
  outcome: string;
};

export type PracticalExampleLens = {
  constraints: string[];
  artifacts: string[];
  failureSignals: string[];
  reviewQuestions: string[];
};

const example = (scenario: string, actions: string[], outcome: string): PracticalExample => ({
  scenario,
  actions,
  outcome,
});

const lens = (
  constraints: string[],
  artifacts: string[],
  failureSignals: string[],
  reviewQuestions: string[],
): PracticalExampleLens => ({
  constraints,
  artifacts,
  failureSignals,
  reviewQuestions,
});

const DEFAULT_LENS = lens(
  ["작업 범위, 비목표, 완료 기준을 먼저 적는다.", "결과는 말이 아니라 테스트, 로그, 문서, 화면 캡처 중 하나로 남긴다."],
  ["작업 전 가정", "검증 결과", "남은 리스크"],
  ["완료 기준이 감상문처럼 쓰인다.", "작업 후 재현 가능한 증거가 남지 않는다."],
  ["이 작업이 실패하면 사용자나 운영에 어떤 영향이 있는가?", "다음 사람이 같은 판단을 반복할 수 있는가?"],
);

const LENSES: Record<string, PracticalExampleLens> = {
  home: lens(
    ["읽는 순서보다 현재 프로젝트의 병목을 먼저 정한다.", "학습 주제는 이번 주 작업과 연결되는 것만 고른다."],
    ["학습 로드맵", "이번 주 적용 항목", "검증 로그"],
    ["문서를 많이 읽었지만 실제 작업 산출물이 없다.", "메뉴를 순서대로 소비하느라 현재 병목을 놓친다."],
    ["이번 주 작업의 가장 약한 경계면은 어디인가?", "읽은 내용을 어떤 PR이나 운영 절차에 반영했는가?"],
  ),
  backend: lens(
    ["API 계약, 트랜잭션, 권한, 관측 가능성을 한 세트로 본다.", "운영 중 재시도와 중복 요청을 정상 입력으로 가정한다."],
    ["API contract", "테스트 케이스", "트랜잭션/멱등성 메모", "로그 필드 목록"],
    ["happy path만 통과한다.", "실패 응답, 중복 요청, 권한 오류가 설계 밖에 있다."],
    ["이 API는 재시도돼도 안전한가?", "장애가 나면 traceId만으로 원인을 좁힐 수 있는가?"],
  ),
  frontend: lens(
    ["화면 상태는 loading, empty, error, permission denied까지 포함한다.", "성능·접근성·보안은 구현 후 장식이 아니라 PR 완료 기준이다."],
    ["상태별 화면 캡처", "Web Vitals 또는 Lighthouse 결과", "접근성 체크 결과", "핵심 플로우 테스트"],
    ["시각적으로는 맞지만 키보드/느린 네트워크/오류 상태에서 깨진다.", "렌더링 병목을 측정하지 않고 memo만 추가한다."],
    ["사용자가 실패했을 때 회복 경로가 있는가?", "이 최적화는 실제 지표를 개선했는가?"],
  ),
  network: lens(
    ["항상 source, destination, route, policy, DNS, service 순서로 좁힌다.", "터널 UP과 서비스 통신 성공을 같은 의미로 보지 않는다."],
    ["패킷 경로 메모", "route table 캡처", "방화벽 규칙", "tcpdump/nc/curl 결과"],
    ["ping 하나로 네트워크 정상/비정상을 판단한다.", "return path와 고객사 방화벽을 확인하지 않는다."],
    ["패킷의 다음 홉은 무엇인가?", "응답 패킷은 같은 경로로 돌아올 수 있는가?"],
  ),
  devops: lens(
    ["자동화보다 먼저 재현성, 추적성, 롤백 가능성을 확보한다.", "배포 파이프라인은 빌드가 아니라 변경 관리 시스템이다."],
    ["pipeline run", "artifact digest", "배포 승인 기록", "rollback checklist", "배포 후 지표"],
    ["CI는 통과하지만 어떤 artifact가 배포됐는지 모른다.", "롤백이 문서에만 있고 실제로 검증되지 않았다."],
    ["이 변경은 같은 입력으로 다시 빌드 가능한가?", "배포 후 나빠지면 무엇을 보고 멈추는가?"],
  ),
  ax: lens(
    ["AI에게 맡길 권한과 중단 조건을 작업 전에 정한다.", "생성 속도보다 rework, review latency, defect escape를 본다."],
    ["task spec", "context package", "tool trace", "episode package", "failure classification"],
    ["AI가 만든 결과를 AI가 스스로 승인한다.", "프롬프트만 개선하고 업무 분해나 검증 기준은 그대로 둔다."],
    ["이 업무는 자동화, 반자동, read-only 중 어디에 속하는가?", "실패하면 사람이 어느 지점에서 개입하는가?"],
  ),
  design: lens(
    ["디자인은 화면 장식이 아니라 문제 정의, 흐름, 상태, 제약의 구조화다.", "개발 handoff 전에 edge state와 QA 기준을 확정한다."],
    ["user flow", "상태 목록", "컴포넌트 계약", "접근성 기준", "handoff checklist"],
    ["happy path 시안만 있고 오류/권한/빈 상태가 없다.", "디자인 변경이 토큰과 컴포넌트 계약에 반영되지 않는다."],
    ["사용자가 다음 행동을 즉시 알 수 있는가?", "구현자가 디자인 의도를 추측하지 않아도 되는가?"],
  ),
  examples: lens(
    ["문법 예제는 운영 제약과 연결될 때 실무 가치가 생긴다.", "예제 코드는 실패 케이스와 디버깅 명령까지 포함해야 한다."],
    ["작동 예제", "실패 예제", "디버깅 명령", "운영 주의점"],
    ["예제는 실행되지만 실제 프로젝트 구조에 적용할 기준이 없다.", "에러가 났을 때 어디를 봐야 하는지 설명하지 않는다."],
    ["이 예제는 어떤 운영 문제를 줄이는가?", "실패하면 어떤 로그나 명령으로 확인하는가?"],
  ),
  practical: lens(
    ["가이드는 재현 가능해야 하며 개인 기억에 의존하면 안 된다.", "secret, 환경 차이, rollback 조건을 절차 안에 넣는다."],
    ["체크리스트", "명령 로그", "환경 변수 표", "복구 절차", "검증 결과"],
    ["한 번은 됐지만 다른 PC나 CI에서 재현되지 않는다.", "위험 명령의 대상 환경을 구분하지 않는다."],
    ["다른 사람이 같은 절차로 성공할 수 있는가?", "실수했을 때 되돌리는 방법이 문서에 있는가?"],
  ),
};

const LENS_BY_ITEM_ID: Record<string, keyof typeof LENSES> = {
  home: "home",
  backend: "backend",
  db: "backend",
  "auth-security": "backend",
  architecture: "backend",
  "async-messaging": "backend",
  testing: "backend",
  "docker-deploy": "backend",
  observability: "backend",
  linux: "practical",
  vi: "practical",
  frontend: "frontend",
  "frontend-browser": "frontend",
  "frontend-accessibility": "frontend",
  "frontend-rendering": "frontend",
  "frontend-performance": "frontend",
  "frontend-devtools": "frontend",
  "frontend-security": "frontend",
  "frontend-testing": "frontend",
  "frontend-deployment": "frontend",
  network: "network",
  "network-vpc": "network",
  "network-routing": "network",
  "network-nat-routing": "network",
  "network-firewall": "network",
  "network-dns": "network",
  "network-ipsec": "network",
  "network-cloud-vpn": "network",
  "network-debugging": "network",
  "network-troubleshooting": "network",
  "network-checklist": "network",
  devops: "devops",
  "devops-delivery": "devops",
  "devops-configuration": "devops",
  "devops-ci": "devops",
  "devops-cd": "devops",
  "devops-secrets": "devops",
  "devops-iac": "devops",
  "devops-containers": "devops",
  "devops-orchestration": "devops",
  "devops-observability": "devops",
  "devops-security-reliability": "devops",
  ax: "ax",
  "ax-capability": "ax",
  "ax-automation": "ax",
  "ax-harness": "ax",
  "ax-context": "ax",
  "ax-loop": "ax",
  "ax-multi-agent": "ax",
  "ax-verification": "ax",
  "ax-governance": "ax",
  "ax-organization": "ax",
  "ax-case-studies": "ax",
  "ax-playbook": "ax",
  design: "design",
  "design-ux-thinking": "design",
  "design-information-architecture": "design",
  "design-user-flows": "design",
  "design-layout-hierarchy": "design",
  "design-interaction-patterns": "design",
  "design-forms-input": "design",
  "design-component-patterns": "design",
  "design-system-tokens": "design",
  "design-accessibility-inclusive": "design",
  "design-prototyping-testing": "design",
  "design-handoff-qa": "design",
  "cheat-frontend": "practical",
  "cheat-backend": "practical",
  "cheat-database": "practical",
  "cheat-network": "practical",
  "cheat-devops": "practical",
  "cheat-linux": "practical",
  "cheat-docker": "practical",
  "cheat-interview": "practical",
  "ex-java": "examples",
  "ex-jpa": "examples",
  "ex-spring": "examples",
  "ex-docker": "examples",
  "ex-nginx": "examples",
  "ex-redis": "examples",
  "ex-postgresql": "examples",
  "fullstack-roadmap": "practical",
  "machine-setup": "practical",
  "dev-playbook": "practical",
  gradle: "practical",
  "package-managers": "practical",
  config: "practical",
  "db-seeding": "practical",
  cicd: "practical",
  "logs-tooling": "practical",
};

export const getPracticalExampleLens = (itemId: string): PracticalExampleLens =>
  LENSES[LENS_BY_ITEM_ID[itemId]] ?? DEFAULT_LENS;

export const PRACTICAL_EXAMPLES: Record<string, PracticalExample> = {
  home: example("새 프로젝트를 맡았을 때 핸드북을 읽는 순서를 정한다.", ["홈의 로드맵에서 현재 약한 영역을 표시한다.", "이번 스프린트 작업과 연결되는 메뉴 2개를 고른다.", "작업 전 수용 기준과 검증 명령을 노트로 남긴다."], "학습이 독서로 끝나지 않고 실제 작업의 체크리스트가 된다."),
  backend: example("신규 주문 API를 운영 가능한 기능으로 설계한다.", ["요청/응답 계약과 실패 응답을 먼저 정의한다.", "트랜잭션 경계, 멱등성 키, 로그 필드를 같이 설계한다.", "부하·장애·중복 요청 시나리오를 테스트에 넣는다."], "단순 CRUD가 아니라 추적 가능하고 되돌릴 수 있는 API가 된다."),
  db: example("느린 주문 목록 쿼리를 개선한다.", ["실제 실행 계획과 cardinality를 확인한다.", "필터·정렬·페이지네이션에 맞는 복합 인덱스를 검토한다.", "변경 전후 latency와 lock 위험을 기록한다."], "인덱스를 감으로 추가하지 않고 쿼리 패턴과 운영 비용을 함께 판단한다."),
  "auth-security": example("관리자 전용 기능의 인가 누락을 점검한다.", ["라우트 보호와 서버 측 권한 검사를 분리해 확인한다.", "소유자 변경, 역할 변경, 만료 토큰 케이스를 테스트한다.", "감사 로그에 actor, target, action, result를 남긴다."], "프론트 가드에 의존하지 않는 서버 중심 보안 경계가 생긴다."),
  architecture: example("기존 모놀리스 일부를 분리할지 판단한다.", ["변경 빈도, 데이터 소유권, 장애 전파, 팀 경계를 표로 정리한다.", "strangler fig 또는 모듈화 중 더 작은 선택지를 먼저 검토한다.", "분리 후 생길 네트워크·트랜잭션 비용을 ADR에 남긴다."], "유행이 아니라 비용과 경계를 근거로 아키텍처 결정을 내린다."),
  "async-messaging": example("결제 완료 후 알림 발송을 비동기로 분리한다.", ["outbox 테이블과 consumer idempotency key를 설계한다.", "재시도, poison message, DLQ 처리 기준을 정한다.", "consumer lag과 실패율 알림을 추가한다."], "사용자 요청 경로는 가벼워지고, 실패한 후속 작업은 추적 가능해진다."),
  testing: example("버그 수정 전에 회귀 테스트를 만든다.", ["사용자 재현 조건을 테스트 이름과 fixture로 고정한다.", "실패 테스트를 먼저 확인한 뒤 최소 수정한다.", "수정 후 관련 contract/integration test까지 실행한다."], "수정이 증상만 막은 것인지 실제 원인을 고친 것인지 구분된다."),
  "docker-deploy": example("Spring Boot 앱을 컨테이너로 배포한다.", ["multi-stage build로 이미지 크기를 줄인다.", "readiness/liveness, graceful shutdown, env 주입을 확인한다.", "롤백 가능한 태그와 이미지 digest를 기록한다."], "개발 환경에서만 도는 이미지가 아니라 운영 런타임 기준을 갖춘다."),
  observability: example("API 5xx 증가 원인을 좁힌다.", ["RED 지표로 요청률, 오류율, 지연을 본다.", "traceId로 특정 요청의 API, DB, 외부 호출 구간을 연결한다.", "로그 high-cardinality 필드를 줄이고 핵심 context를 남긴다."], "증상을 보는 대시보드에서 원인을 좁히는 관측 체계로 이동한다."),
  linux: example("서버에서 디스크 사용량 급증을 조사한다.", ["df, du, lsof로 파일시스템과 삭제된 열린 파일을 확인한다.", "journal/logrotate 설정을 점검한다.", "삭제 전 서비스 영향과 재발 방지 설정을 기록한다."], "명령을 외우는 수준을 넘어 운영 사고를 안전하게 처리한다."),
  vi: example("운영 서버에서 설정 파일을 빠르게 수정한다.", ["검색으로 대상 키를 찾고 ciw, ci\", dd 같은 작은 명령만 사용한다.", "수정 전 원본을 백업하고 diff로 변경을 확인한다.", "저장 후 서비스 reload와 rollback 경로를 확인한다."], "vi를 탈출하는 도구가 아니라 서버 작업의 안전한 편집기로 쓴다."),
  frontend: example("대시보드 첫 화면을 제품 수준으로 점검한다.", ["핵심 사용자 흐름, empty/loading/error 상태를 점검한다.", "API latency와 렌더링 병목을 분리한다.", "접근성, 성능, 보안, 배포 체크를 PR에 남긴다."], "화면 구현을 넘어 사용자 경험과 운영 품질을 같이 관리한다."),
  "frontend-browser": example("버튼 클릭 후 화면이 멈추는 문제를 분석한다.", ["event loop, long task, layout/recalc style 여부를 Performance 탭에서 확인한다.", "DOM 업데이트와 네트워크 대기 시간을 분리한다.", "불필요한 synchronous 작업을 worker 또는 idle 처리로 옮긴다."], "브라우저 내부 동작을 기준으로 체감 성능 문제를 설명한다."),
  "frontend-accessibility": example("모달 컴포넌트를 접근성 기준으로 개선한다.", ["focus trap, Escape 닫기, aria-labelledby를 확인한다.", "키보드만으로 열기·닫기·액션 실행을 테스트한다.", "스크린리더에서 제목과 설명이 읽히는지 확인한다."], "마우스 사용자뿐 아니라 보조 기술 사용자도 같은 흐름을 완료한다."),
  "frontend-rendering": example("검색 페이지의 불필요한 리렌더링을 줄인다.", ["React DevTools Profiler로 렌더링 원인을 찾는다.", "memoization 전에 state 위치와 props 안정성을 먼저 점검한다.", "번들 분리와 Suspense 경계가 사용자 흐름에 맞는지 본다."], "메모이제이션을 남발하지 않고 실제 병목에 맞는 최적화를 한다."),
  "frontend-performance": example("릴리즈 전 성능 회귀를 막는다.", ["Lighthouse와 Web Vitals baseline을 저장한다.", "LCP 이미지, CLS 원인, INP long task를 항목별로 확인한다.", "CI에 bundle size와 주요 route 성능 예산을 둔다."], "성능을 사후 감상이 아니라 릴리즈 게이트로 다룬다."),
  "frontend-devtools": example("운영에서만 느린 화면을 재현한다.", ["Network throttling과 CPU slowdown으로 조건을 맞춘다.", "Performance, Memory, Coverage 탭을 순서대로 확인한다.", "원인 후보와 캡처 파일을 PR 또는 이슈에 첨부한다."], "DevTools를 디버깅 감각이 아니라 재현 가능한 분석 도구로 쓴다."),
  "frontend-security": example("사용자 입력이 포함된 알림 메시지를 렌더링한다.", ["innerHTML 사용 여부와 escape 경로를 확인한다.", "CSP, trusted types, URL allowlist를 점검한다.", "권한 판단이 클라이언트에만 있지 않은지 API와 맞춘다."], "XSS와 인가 우회를 UI 구현 단계에서 예방한다."),
  "frontend-testing": example("결제 폼의 테스트 전략을 짠다.", ["validation unit test, user flow integration test, API mock 시나리오를 나눈다.", "실패 결제, 중복 클릭, 네트워크 지연을 포함한다.", "Playwright로 핵심 happy path와 error path를 검증한다."], "테스트가 스냅샷 보존이 아니라 사용자 위험을 줄인다."),
  "frontend-deployment": example("정적 프론트엔드를 CDN으로 배포한다.", ["immutable asset과 HTML cache 정책을 분리한다.", "환경변수 중 public config와 secret을 구분한다.", "canary 또는 preview URL에서 API 호환성을 확인한다."], "빠른 배포와 안전한 롤백이 가능한 프론트 배포 체계를 만든다."),
  network: example("서비스 접속 실패를 네트워크 관점으로 분해한다.", ["source, destination, route, firewall, DNS, service를 순서대로 확인한다.", "L3/L4/L7 중 실패 지점을 기록한다.", "고객사 또는 클라우드 담당자에게 필요한 증거를 정리한다."], "막연한 '네트워크 문제'를 계층별 원인으로 좁힌다."),
  "network-vpc": example("신규 VPC CIDR을 정한다.", ["사내망, 고객사망, 클라우드 기본 대역과 겹치지 않는지 확인한다.", "public/private/db subnet 크기를 예상 성장량에 맞춰 나눈다.", "reserved IP와 AZ 확장 여지를 남긴다."], "나중에 VPN이나 peering에서 대역 충돌로 막히지 않는다."),
  "network-routing": example("private API 서버를 인터넷에서 직접 숨긴다.", ["public subnet에는 LB/bastion만 둔다.", "API 서버는 private subnet에 두고 route table을 분리한다.", "접근 경로를 LB 또는 bastion으로 제한한다."], "리소스 노출 범위가 subnet과 route table로 설명된다."),
  "network-nat-routing": example("private subnet 서버에서 패키지 설치가 실패한다.", ["0.0.0.0/0 route가 NAT Gateway를 향하는지 확인한다.", "NAT 상태와 security group outbound를 본다.", "return path와 DNS resolution을 같이 점검한다."], "인터넷 접근 실패를 NAT, 라우팅, 방화벽으로 분리한다."),
  "network-firewall": example("고객사에서 API 8080 접근이 안 된다.", ["route가 있는지 먼저 보고 security group inbound를 확인한다.", "source CIDR과 protocol/port가 실제 고객사 대역과 맞는지 검증한다.", "NACL stateless 응답 규칙까지 확인한다."], "방화벽을 '열었다'가 아니라 어떤 방향과 대역을 허용했는지 설명한다."),
  "network-dns": example("VPN 너머 내부 도메인이 해석되지 않는다.", ["클라이언트가 어떤 resolver를 쓰는지 확인한다.", "private hosted zone 또는 conditional forwarder 설정을 점검한다.", "TTL과 split-horizon DNS로 인한 차이를 기록한다."], "도메인 문제를 애플리케이션 장애로 오해하지 않는다."),
  "network-ipsec": example("IPsec 터널이 주기적으로 끊긴다.", ["Phase 1/2 lifetime, DH group, PFS, PSK 값을 양쪽과 대조한다.", "rekey 시점의 로그와 터널 상태를 확인한다.", "트래픽 selector와 NAT-T 필요 여부를 점검한다."], "터널 UP/DOWN을 암호화 협상과 라우팅 문제로 분리한다."),
  "network-cloud-vpn": example("클라우드 VPN Gateway를 고객사와 연동한다.", ["local/peer CIDR, peer public IP, IKE 파라미터를 체크리스트로 합의한다.", "private subnet route table에 고객사 대역을 추가한다.", "ACG와 고객사 방화벽 양쪽 허용을 확인한다."], "콘솔 설정과 고객사 협의 항목이 누락 없이 맞물린다."),
  "network-debugging": example("API health check가 timeout 난다.", ["ping 대신 nc로 포트 도달성을 확인한다.", "traceroute와 tcpdump로 패킷 경로와 응답 여부를 본다.", "마지막에 curl -v로 HTTP/TLS 문제를 확인한다."], "도구를 증상별로 골라 L3에서 L7까지 좁힌다."),
  "network-troubleshooting": example("어제 되던 VPN DB 연결이 오늘 실패한다.", ["터널 상태와 rekey 로그를 확인한다.", "고객사 public IP, route table, 방화벽 변경 이력을 확인한다.", "tcpdump로 outbound만 나가는지 응답이 오는지 본다."], "장애 원인을 우리쪽/고객사쪽/터널 협상으로 나눠 요청할 수 있다."),
  "network-checklist": example("VPN 구축 전 사전 점검 회의를 준비한다.", ["CIDR 충돌, peer IP, Phase 1/2, 포트, DNS, 검증 명령을 표로 만든다.", "역방향 라우팅과 고객사 방화벽 담당자를 확인한다.", "검증 일정과 rollback 기준을 합의한다."], "VPN 작업이 콘솔 조작이 아니라 양쪽 네트워크 변경으로 관리된다."),
  devops: example("팀 배포 흐름을 점검한다.", ["요구사항부터 운영까지 value stream을 그린다.", "수동 승인, 대기, 재작업 지점을 표시한다.", "자동화보다 먼저 일관성과 복구 가능성을 개선한다."], "DevOps를 도구 목록이 아니라 전달 시스템 개선으로 이해한다."),
  "devops-delivery": example("기능 배포 단위를 줄인다.", ["변경 단위와 릴리스 단위를 분리한다.", "feature flag와 backward compatible API를 설계한다.", "작은 배포 후 관측 지표로 영향을 확인한다."], "큰 릴리즈 위험을 작은 검증 가능한 변경으로 낮춘다."),
  "devops-configuration": example("릴리즈 기준선을 남긴다.", ["commit SHA, image digest, migration version, config version을 묶는다.", "release tag와 changelog를 연결한다.", "권한 있는 사람만 production 기준선을 만들게 한다."], "문제가 생겼을 때 어떤 코드와 설정이 배포됐는지 추적된다."),
  "devops-ci": example("PR마다 품질 게이트를 구성한다.", ["lint, typecheck, unit, integration test를 빠른 순서로 배치한다.", "실패 시 원인 로그를 바로 보이게 한다.", "flaky test와 느린 테스트를 별도 관리한다."], "CI가 형식적 통과가 아니라 빠른 피드백 시스템이 된다."),
  "devops-cd": example("무중단 배포 전략을 고른다.", ["서비스 특성에 따라 rolling, blue-green, canary를 비교한다.", "배포 후 metric gate와 rollback trigger를 정한다.", "DB 변경은 expand-contract로 분리한다."], "배포는 자동 실행이 아니라 검증과 복구가 포함된 흐름이 된다."),
  "devops-secrets": example("노출된 API key를 처리한다.", ["먼저 key를 revoke하고 새 key를 발급한다.", "로그, git history, CI output 노출 범위를 확인한다.", "secret scanning과 rotation 절차를 추가한다."], "비밀 삭제가 아니라 권한 폐기와 재발 방지로 대응한다."),
  "devops-iac": example("Terraform 변경을 안전하게 적용한다.", ["plan에서 생성/수정/삭제 리소스를 검토한다.", "state lock, drift, dependency를 확인한다.", "production 적용 전 staging에서 같은 module로 검증한다."], "인프라 변경도 코드 리뷰와 실행 계획 기준으로 다룬다."),
  "devops-containers": example("컨테이너 OOM 문제를 해결한다.", ["request/limit과 실제 memory usage를 비교한다.", "heap, native memory, sidecar 사용량을 분리한다.", "graceful shutdown과 probe 실패 패턴을 같이 본다."], "컨테이너를 이미지가 아니라 제한된 런타임으로 이해한다."),
  "devops-orchestration": example("Kubernetes 배포가 rollout 중 멈춘다.", ["pod event, readiness probe, image pull, resource scheduling을 확인한다.", "service selector와 deployment label이 맞는지 본다.", "rollback과 progressive rollout 조건을 점검한다."], "클러스터 문제를 선언 모델과 컨트롤러 동작으로 해석한다."),
  "devops-observability": example("알림이 너무 많이 울리는 문제를 줄인다.", ["사용자 영향이 있는 SLI 중심으로 알림을 재정의한다.", "burn rate와 severity 기준을 분리한다.", "대시보드는 원인 탐색 순서대로 재배치한다."], "알림 피로를 줄이고 실제 장애 대응 속도를 높인다."),
  "devops-security-reliability": example("백업 정책이 믿을 만한지 검증한다.", ["RPO/RTO를 정하고 restore drill을 실행한다.", "복구된 데이터 무결성과 앱 기동을 확인한다.", "훈련 결과를 runbook과 알림 기준에 반영한다."], "백업 파일 보유가 아니라 복구 가능성이 검증된다."),
  ax: example("반복되는 PR 리뷰 보조를 AX 업무로 설계한다.", ["risk map, test gap, security concern을 출력하는 task spec을 만든다.", "AI는 comment draft만 만들고 approve 권한은 주지 않는다.", "false positive와 review latency를 측정한다."], "AI 사용이 개인 팁이 아니라 검증 가능한 업무 시스템이 된다."),
  "ax-capability": example("팀 내 AX 역량 갭을 진단한다.", ["Workflow Mining, Context Engineering, Evaluation, Governance 역량을 표로 점검한다.", "각자 반복 업무 episode를 3개씩 가져온다.", "자동화 후보와 금지 업무를 구분한다."], "프롬프트 실력보다 업무 자동화 설계 역량을 키운다."),
  "ax-automation": example("장애 회고 초안을 자동화한다.", ["incident ticket, deploy log, metric, trace를 context package로 묶는다.", "AI는 timeline과 원인 후보만 만들게 한다.", "사람이 최종 root cause와 action item을 승인한다."], "고위험 판단은 남기고 자료 수집과 초안 작성 비용을 줄인다."),
  "ax-harness": example("문서 동기화 agent의 하네스를 만든다.", ["API diff와 관련 문서를 context builder로 수집한다.", "문서 파일 write만 허용하고 코드 write는 금지한다.", "link check와 example request 검증을 gate로 둔다."], "작은 권한과 명확한 검증으로 자동화 위험을 낮춘다."),
  "ax-context": example("AI에게 결제 버그 수정을 맡기기 전 컨텍스트를 구성한다.", ["상태 전이표, webhook spec, 관련 테스트, 최근 장애를 포함한다.", "불필요한 전체 레포 요약은 제외한다.", "출처와 신뢰 수준을 표시한다."], "모델 성능보다 컨텍스트 품질로 결과 안정성을 높인다."),
  "ax-loop": example("AI 수정이 세 번 실패한 작업을 멈춘다.", ["각 루프의 가설, 수정, 검증 결과를 기록한다.", "실패 원인이 spec, context, tool, test 중 무엇인지 분류한다.", "중단 조건에 도달하면 사람 설계 리뷰로 전환한다."], "반복 생성이 아니라 학습 가능한 루프로 운영한다."),
  "ax-multi-agent": example("대규모 리팩터링을 역할별 agent로 나눈다.", ["planner, implementer, test writer, reviewer를 분리한다.", "각 agent는 다른 worktree 또는 명확한 파일 범위를 갖는다.", "통합자는 diff 충돌과 검증 결과만 보고 merge한다."], "병렬 작업을 하되 책임 경계와 통합 품질을 유지한다."),
  "ax-verification": example("AI가 만든 테스트를 검증한다.", ["테스트가 실제로 기존 코드에서 실패하는지 확인한다.", "AI가 놓친 adversarial case를 별도 추가한다.", "episode package에 명령 결과와 실패 분류를 남긴다."], "AI 산출물의 신뢰를 말이 아니라 증거로 판단한다."),
  "ax-governance": example("AI 도구에 고객 데이터를 넣어도 되는지 정책화한다.", ["데이터 등급, redaction 기준, 금지 입력을 정의한다.", "tool permission과 audit log를 연결한다.", "위반 사례와 승인 예외 절차를 문서화한다."], "AI 사용이 암묵적 관행이 아니라 감사 가능한 운영 정책이 된다."),
  "ax-organization": example("전사 AI 도입 파일럿을 설계한다.", ["baseline, pilot team, workflow, metric을 먼저 정한다.", "read-only 업무부터 시작해 policy gate를 둔다.", "cohort 확장 전에 rework와 defect escape를 확인한다."], "도구 배포가 아니라 조직의 전달 시스템 개선으로 도입한다."),
  "ax-case-studies": example("팀에 맞는 AX 적용 사례를 고른다.", ["대규모 조직 사례와 셀 단위 사례를 비교한다.", "우리 팀의 반복 업무를 problem, harness, verification, metrics로 재작성한다.", "실패 사례의 근본 원인을 사전 체크리스트로 바꾼다."], "성공담을 모방하지 않고 우리 팀의 업무 경계에 맞게 적용한다."),
  "ax-playbook": example("2주 AX 자동화 스프린트를 실행한다.", ["Day 1에 업무와 baseline을 정한다.", "read-only 분석에서 작은 write 권한으로 단계적으로 확장한다.", "마지막 날 cost per episode와 rework로 지속 여부를 결정한다."], "AI 자동화를 작게 실험하고 증거 기반으로 확장한다."),
  design: example("새 기능을 디자인 관점에서 재검토한다.", ["사용자 문제와 성공 지표를 먼저 쓴다.", "정보구조, 흐름, 상태, 접근성, handoff를 차례로 본다.", "개발 전 edge state와 QA 기준을 합의한다."], "예쁜 화면이 아니라 작동하는 제품 경험을 설계한다."),
  "design-ux-thinking": example("요구사항이 모호한 기능을 정리한다.", ["사용자 job과 pain point를 분리한다.", "문제 가설과 성공 지표를 한 문장으로 쓴다.", "만들지 않을 범위와 리스크를 명시한다."], "솔루션 논쟁 전에 문제 정의를 맞춘다."),
  "design-information-architecture": example("관리자 메뉴가 커져 찾기 어려운 문제를 해결한다.", ["card sorting으로 사용자 mental model을 확인한다.", "상위 메뉴와 하위 태스크를 재분류한다.", "tree testing으로 탐색 성공률을 검증한다."], "메뉴 구조가 조직도가 아니라 사용자 작업 기준으로 정리된다."),
  "design-user-flows": example("회원가입 이탈률을 줄인다.", ["필수 단계와 나중에 받아도 되는 정보를 분리한다.", "오류, 재시도, 이메일 인증 실패 흐름을 그린다.", "각 단계의 drop-off 지표를 연결한다."], "happy path가 아니라 실제 사용자의 중단과 회복 흐름까지 설계한다."),
  "design-layout-hierarchy": example("복잡한 설정 화면을 정리한다.", ["가장 자주 쓰는 액션과 위험한 액션을 분리한다.", "섹션 제목, 설명, 컨트롤 간 위계를 조정한다.", "모바일에서 스캔 순서가 유지되는지 확인한다."], "정보량이 많아도 사용자가 우선순위를 읽을 수 있다."),
  "design-interaction-patterns": example("삭제 액션의 실수 비용을 줄인다.", ["undo, confirmation, delayed delete 중 위험도에 맞게 고른다.", "파괴적 액션은 위치와 색상, 문구를 명확히 한다.", "키보드와 스크린리더에서도 같은 보호가 있는지 확인한다."], "사용자 실수를 막는 인터랙션 패턴을 비용에 맞춰 적용한다."),
  "design-forms-input": example("사업자 정보 입력 폼을 개선한다.", ["필드 그룹, 입력 마스크, 서버 검증 메시지를 정리한다.", "저장 실패 후 입력값 보존과 focus 이동을 확인한다.", "부분 저장 또는 임시 저장 필요성을 판단한다."], "폼이 데이터 수집 UI가 아니라 오류 회복 가능한 작업 흐름이 된다."),
  "design-component-patterns": example("테이블 필터 컴포넌트를 표준화한다.", ["검색, 정렬, 필터, pagination의 상태 모델을 통일한다.", "empty/loading/error 상태를 컴포넌트 계약에 포함한다.", "URL state와 접근성 label을 함께 설계한다."], "반복 UI가 매번 다르게 구현되지 않고 제품 일관성을 만든다."),
  "design-system-tokens": example("브랜드 컬러 변경을 제품 전체에 적용한다.", ["semantic token과 raw color를 분리한다.", "컴포넌트 상태별 토큰 사용을 점검한다.", "visual regression으로 주요 화면을 확인한다."], "색상 변경이 CSS 검색 작업이 아니라 시스템 변경이 된다."),
  "design-accessibility-inclusive": example("데이터 테이블 접근성을 점검한다.", ["header scope, caption, sort 상태, keyboard navigation을 확인한다.", "색만으로 상태를 구분하지 않게 한다.", "확대/고대비/스크린리더 조건에서 테스트한다."], "특정 사용자만 쓸 수 있는 UI가 아니라 더 넓은 조건에서 견딘다."),
  "design-prototyping-testing": example("새 온보딩 흐름을 검증한다.", ["클릭 가능한 프로토타입으로 첫 과업을 만들게 한다.", "사용자가 멈춘 지점과 질문을 기록한다.", "정량 설문보다 관찰 기반 수정 포인트를 우선한다."], "개발 전 큰 사용성 실패를 저렴하게 발견한다."),
  "design-handoff-qa": example("디자인과 구현의 차이를 줄인다.", ["Figma spec, token, responsive behavior, 상태 목록을 handoff에 포함한다.", "개발 완료 후 visual diff와 interaction QA를 실행한다.", "디자인 변경은 changelog로 남긴다."], "handoff가 파일 전달이 아니라 구현 품질 관리 절차가 된다."),
  "cheat-frontend": example("성능 이슈가 있는 화면을 점검하면서 렌더링, 상태, 접근성 체크 기준을 빠르게 확인한다.", ["DevTools로 렌더링과 네트워크 병목을 분리한다.", "서버 상태와 UI 상태가 섞인 지점을 정리한다.", "핵심 사용자 흐름의 접근성, 보안, 테스트 누락을 체크한다."], "프론트엔드 개선 후보가 측정 근거, 상태 경계, 사용자 영향 기준으로 정리된다."),
  "cheat-backend": example("API 변경 리뷰 전에 인증, 검증, 트랜잭션, idempotency 기준을 빠르게 확인한다.", ["요청/응답 contract와 validation 위치를 점검한다.", "인증과 인가 책임이 분리되어 있는지 확인한다.", "재시도와 중복 요청에 안전한 처리 기준을 표시한다."], "API 리뷰에서 깨질 수 있는 contract, 권한, 중복 처리 위험이 먼저 드러난다."),
  "cheat-database": example("쿼리 성능이나 마이그레이션 리뷰 전에 인덱스, 실행 계획, 트랜잭션 위험을 확인한다.", ["WHERE, JOIN, ORDER BY 조건과 인덱스 방향을 맞춰 본다.", "실행 계획에서 scan, join, sort 비용을 확인한다.", "스키마 변경의 lock, rollback, data verification 계획을 점검한다."], "DB 변경이 성능과 운영 안전성 기준으로 설명 가능한 상태가 된다."),
  "cheat-network": example("서비스 연결 장애를 DNS, 포트, TLS, HTTP 단계로 나눠 좁힌다.", ["DNS 해석 결과와 TTL을 확인한다.", "대상 포트 연결성과 방화벽 경로를 점검한다.", "HTTP 응답과 TLS 핸드셰이크 로그를 분리해 본다."], "연결 장애가 이름 해석, 네트워크 경로, 프로토콜 중 어느 층의 문제인지 좁혀진다."),
  "cheat-devops": example("배포 전 CI/CD, rollback, observability, secret 기준을 빠르게 확인한다.", ["빌드, 테스트, 배포, 승인 gate가 분리되어 있는지 본다.", "rollback이 앱과 DB 변경 모두에서 가능한지 확인한다.", "배포 후 볼 지표와 로그 위치를 미리 정한다."], "배포 위험이 pipeline gate, rollback 가능성, 관측 지표 기준으로 정리된다."),
  "cheat-linux": example("운영 서버에서 포트, 프로세스, 로그, 디스크 문제를 빠르게 조사한다.", ["프로세스와 포트 점유 상태를 확인한다.", "최근 로그에서 에러 패턴을 찾는다.", "디스크, 메모리, CPU 사용량을 확인한다."], "서버 이상 징후가 프로세스, 네트워크, 리소스, 로그 중 어디에서 시작됐는지 드러난다."),
  "cheat-docker": example("컨테이너 실행 오류를 이미지, 환경변수, 포트, 볼륨, 네트워크 기준으로 점검한다.", ["이미지 빌드 로그와 Dockerfile cache 경계를 확인한다.", "컨테이너 로그, 포트 매핑, 환경변수를 점검한다.", "볼륨과 compose 네트워크 이름 해석을 확인한다."], "컨테이너 문제가 빌드, 런타임 설정, 네트워크, 상태 저장 중 어디인지 좁혀진다."),
  "cheat-interview": example("면접 답변을 준비하면서 답변 길이, 경험 수준, 꼬리질문 대응을 정리한다.", ["질문별 30초 결론과 90초 근거를 나눈다.", "직접 경험, 일부 경험, 개념 지식을 구분해 표현한다.", "모르는 질문에는 추론 과정과 확인 계획을 함께 말한다."], "답변이 과장 없이 결론, 근거, trade-off, 경험 증거 순서로 정리된다."),
  "ex-java": example("null 처리 버그를 Java 코드에서 줄인다.", ["Optional 사용 위치와 금지 위치를 구분한다.", "불변 객체와 명시적 예외로 계약을 드러낸다.", "테스트에 null, empty, invalid case를 넣는다."], "문법 예제를 실제 안정적인 Java 코드 작성 기준으로 연결한다."),
  "ex-jpa": example("N+1 쿼리를 해결한다.", ["로그로 실제 쿼리 수를 확인한다.", "fetch join, entity graph, batch size 중 조회 목적에 맞게 고른다.", "pagination과 cartesian product 위험을 같이 검토한다."], "JPA 편의성 뒤의 SQL 비용을 통제한다."),
  "ex-spring": example("Spring Boot API에 전역 예외 처리를 추가한다.", ["domain exception과 system exception을 분리한다.", "ControllerAdvice로 error response 형식을 통일한다.", "traceId와 validation field error를 포함한다."], "사용자와 운영자가 모두 이해할 수 있는 오류 응답을 만든다."),
  "ex-docker": example("로컬 개발 환경을 Docker Compose로 통일한다.", ["app, db, redis, migration service를 분리한다.", "volume과 healthcheck, network alias를 명시한다.", "초기 데이터와 reset 명령을 문서화한다."], "팀원이 같은 명령으로 같은 개발 환경을 재현한다."),
  "ex-nginx": example("SPA와 API reverse proxy를 구성한다.", ["static asset cache와 index.html cache를 분리한다.", "API timeout, header forwarding, compression을 설정한다.", "404 fallback이 API 경로를 삼키지 않는지 확인한다."], "nginx가 단순 정적 서버가 아니라 경계 라우터 역할을 한다."),
  "ex-redis": example("인기 상품 캐시를 추가한다.", ["TTL, cache key, invalidation 시점을 정한다.", "cache stampede를 막기 위한 lock 또는 stale-while-revalidate를 검토한다.", "hit ratio와 stale data 위험을 관측한다."], "캐시를 속도 향상뿐 아니라 정합성 거래로 다룬다."),
  "ex-postgresql": example("운영 DB에서 안전하게 컬럼을 추가한다.", ["nullable 컬럼 추가, backfill, constraint validation 순서로 나눈다.", "lock timeout과 statement timeout을 설정한다.", "rollback/forward plan과 row count 검증을 남긴다."], "DDL을 한 번에 실행하지 않고 무중단 변경으로 설계한다."),
  "fullstack-roadmap": example("분기 학습 계획을 세운다.", ["현재 프로젝트의 UI/API/DB/운영 경계면을 하나 고른다.", "관련 핸드북 3개와 capstone 과제를 연결한다.", "주간 결과를 검증 로그와 회고로 남긴다."], "학습 주제가 실제 풀스택 판단 경험으로 쌓인다."),
  "machine-setup": example("새 맥에서 개발 환경을 재현한다.", ["Brewfile, mise, dotfiles, editor 설정을 순서대로 적용한다.", "프로젝트 clone 후 build/test가 통과하는지 확인한다.", "수동 설치 항목과 secret 주입을 별도 문서화한다."], "환경 설정이 기억이 아니라 재현 가능한 절차가 된다."),
  "dev-playbook": example("새 기능 작업을 시작한다.", ["요구사항, 비목표, 수용 기준, 검증 명령을 먼저 적는다.", "작은 diff 단위로 구현하고 각 단계마다 테스트한다.", "PR에 변경 이유, 검증 결과, 남은 위험을 남긴다."], "작업 방식이 매번 즉흥적이지 않고 반복 가능한 품질 루프가 된다."),
  gradle: example("의존성 충돌로 런타임 오류가 난다.", ["dependencyInsight로 선택된 버전과 유입 경로를 확인한다.", "BOM, version catalog, strictly 중 적절한 고정 방식을 고른다.", "clean build와 관련 테스트로 회귀를 확인한다."], "Gradle 문제를 추측이 아니라 의존성 그래프로 해결한다."),
  "package-managers": example("Node 버전 차이로 빌드가 깨진다.", ["package manager와 lockfile, Node version을 고정한다.", "corepack 또는 mise로 팀 버전을 통일한다.", "CI에서 동일 명령으로 install/build를 실행한다."], "로컬과 CI의 패키지 환경 차이를 줄인다."),
  config: example("staging과 production API URL이 섞인다.", ["build-time public config와 runtime secret을 분리한다.", "환경별 config source와 override 순서를 문서화한다.", "앱 시작 시 필수 config validation을 추가한다."], "환경 설정 실수가 배포 후 장애로 이어지는 것을 줄인다."),
  "db-seeding": example("로컬 DB를 매번 같은 상태로 만든다.", ["schema migration과 seed 데이터를 분리한다.", "idempotent seed와 test fixture를 구분한다.", "reset 명령이 개발 DB에만 동작하도록 guard를 둔다."], "개발과 테스트 데이터가 재현 가능하고 안전해진다."),
  cicd: example("배포 파이프라인을 구성한다.", ["install, test, build, image push, deploy 단계를 분리한다.", "branch protection과 environment approval을 설정한다.", "배포 후 smoke test와 rollback 명령을 연결한다."], "CI/CD가 자동 실행뿐 아니라 통제와 복구를 포함한다."),
  "logs-tooling": example("자주 보는 장애 로그를 빠르게 추출한다.", ["서비스명, traceId, error code 기준 필터 명령을 만든다.", "jq, rg, tail 조합을 alias 또는 script로 저장한다.", "민감정보가 출력되지 않도록 masking을 확인한다."], "로그 분석이 매번 수작업 검색이 아니라 반복 가능한 도구가 된다."),
};
